// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (business_id, label, key_prefix, key_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, business_id, label, key_prefix, key_hash, last_used_at, revoked_at, created_at
`

type CreateApiKeyParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Label      string    `json:"label"`
	KeyPrefix  string    `json:"key_prefix"`
	KeyHash    string    `json:"key_hash"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.BusinessID,
		arg.Label,
		arg.KeyPrefix,
		arg.KeyHash,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Label,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getApiKeyByPrefix = `-- name: GetApiKeyByPrefix :one
SELECT id, business_id, label, key_prefix, key_hash, last_used_at, revoked_at, created_at FROM api_keys
WHERE key_prefix = $1
`

func (q *Queries) GetApiKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByPrefix, keyPrefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Label,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listApiKeysByBusiness = `-- name: ListApiKeysByBusiness :many
SELECT id, business_id, label, key_prefix, key_hash, last_used_at, revoked_at, created_at FROM api_keys
WHERE business_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListApiKeysByBusiness(ctx context.Context, businessID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeysByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Label,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiKeysByPrefix = `-- name: ListApiKeysByPrefix :many
SELECT id, business_id, key_hash, revoked_at
FROM api_keys
WHERE key_prefix = $1
`

type ListApiKeysByPrefixRow struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	KeyHash    string             `json:"key_hash"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ListApiKeysByPrefix(ctx context.Context, keyPrefix string) ([]ListApiKeysByPrefixRow, error) {
	rows, err := q.db.Query(ctx, listApiKeysByPrefix, keyPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiKeysByPrefixRow
	for rows.Next() {
		var i ListApiKeysByPrefixRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.KeyHash,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiKey = `-- name: RevokeApiKey :one
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1 AND business_id = $2 AND revoked_at IS NULL
RETURNING id, business_id, label, key_prefix, key_hash, last_used_at, revoked_at, created_at
`

type RevokeApiKeyParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeApiKey, arg.ID, arg.BusinessID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Label,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchApiKeyLastUsed = `-- name: TouchApiKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchApiKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchApiKeyLastUsed, id)
	return err
}
