// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balance_calibrations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createBalanceCalibration = `-- name: CreateBalanceCalibration :one
INSERT INTO balance_calibrations (business_id, device_id, provider_id, balance, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, business_id, device_id, provider_id, balance, note, calibrated_at, created_at
`

type CreateBalanceCalibrationParams struct {
	BusinessID uuid.UUID       `json:"business_id"`
	DeviceID   uuid.UUID       `json:"device_id"`
	ProviderID uuid.UUID       `json:"provider_id"`
	Balance    decimal.Decimal `json:"balance"`
	Note       *string         `json:"note"`
}

func (q *Queries) CreateBalanceCalibration(ctx context.Context, arg CreateBalanceCalibrationParams) (BalanceCalibration, error) {
	row := q.db.QueryRow(ctx, createBalanceCalibration,
		arg.BusinessID,
		arg.DeviceID,
		arg.ProviderID,
		arg.Balance,
		arg.Note,
	)
	var i BalanceCalibration
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.DeviceID,
		&i.ProviderID,
		&i.Balance,
		&i.Note,
		&i.CalibratedAt,
		&i.CreatedAt,
	)
	return i, err
}
