// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: businesses.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO businesses (name, owner_email)
VALUES ($1, $2)
RETURNING id, name, owner_email, status, created_at, updated_at
`

type CreateBusinessParams struct {
	Name       string `json:"name"`
	OwnerEmail string `json:"owner_email"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, createBusiness, arg.Name, arg.OwnerEmail)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusiness = `-- name: GetBusiness :one
SELECT id, name, owner_email, status, created_at, updated_at FROM businesses
WHERE id = $1
`

func (q *Queries) GetBusiness(ctx context.Context, id uuid.UUID) (Business, error) {
	row := q.db.QueryRow(ctx, getBusiness, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessByEmail = `-- name: GetBusinessByEmail :one
SELECT id, name, owner_email, status, created_at, updated_at FROM businesses
WHERE owner_email = $1
LIMIT 1
`

func (q *Queries) GetBusinessByEmail(ctx context.Context, ownerEmail string) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessByEmail, ownerEmail)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBusinesses = `-- name: ListBusinesses :many
SELECT id, name, owner_email, status, created_at, updated_at FROM businesses
ORDER BY created_at DESC
`

func (q *Queries) ListBusinesses(ctx context.Context) ([]Business, error) {
	rows, err := q.db.Query(ctx, listBusinesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Business
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerEmail,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBusinessStatus = `-- name: SetBusinessStatus :one
UPDATE businesses
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, owner_email, status, created_at, updated_at
`

type SetBusinessStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetBusinessStatus(ctx context.Context, arg SetBusinessStatusParams) (Business, error) {
	row := q.db.QueryRow(ctx, setBusinessStatus, arg.ID, arg.Status)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
