// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (business_id, name, token_hash, token_prefix, app_version, os_version)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, name, token_hash, token_prefix, app_version, os_version, last_ping_at, deactivated_at, created_at
`

type CreateDeviceParams struct {
	BusinessID  uuid.UUID `json:"business_id"`
	Name        string    `json:"name"`
	TokenHash   string    `json:"token_hash"`
	TokenPrefix string    `json:"token_prefix"`
	AppVersion  *string   `json:"app_version"`
	OsVersion   *string   `json:"os_version"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.BusinessID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.AppVersion,
		arg.OsVersion,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.AppVersion,
		&i.OsVersion,
		&i.LastPingAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateDevice = `-- name: DeactivateDevice :one
UPDATE devices
SET deactivated_at = now()
WHERE id = $1 AND business_id = $2 AND deactivated_at IS NULL
RETURNING id, business_id, name, token_hash, token_prefix, app_version, os_version, last_ping_at, deactivated_at, created_at
`

type DeactivateDeviceParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) DeactivateDevice(ctx context.Context, arg DeactivateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, deactivateDevice, arg.ID, arg.BusinessID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.AppVersion,
		&i.OsVersion,
		&i.LastPingAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deviceHeartbeat = `-- name: DeviceHeartbeat :exec
UPDATE devices
SET last_ping_at = now()
WHERE id = $1 AND deactivated_at IS NULL
`

func (q *Queries) DeviceHeartbeat(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deviceHeartbeat, id)
	return err
}

const getDeviceByTokenPrefix = `-- name: GetDeviceByTokenPrefix :many
SELECT id, business_id, name, token_hash, token_prefix, app_version, os_version, last_ping_at, deactivated_at, created_at FROM devices
WHERE token_prefix = $1 AND deactivated_at IS NULL
`

func (q *Queries) GetDeviceByTokenPrefix(ctx context.Context, tokenPrefix string) ([]Device, error) {
	rows, err := q.db.Query(ctx, getDeviceByTokenPrefix, tokenPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.AppVersion,
			&i.OsVersion,
			&i.LastPingAt,
			&i.DeactivatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceForBusiness = `-- name: GetDeviceForBusiness :one
SELECT id, business_id, name, token_hash, token_prefix, app_version, os_version, last_ping_at, deactivated_at, created_at FROM devices
WHERE id = $1 AND business_id = $2
`

type GetDeviceForBusinessParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetDeviceForBusiness(ctx context.Context, arg GetDeviceForBusinessParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceForBusiness, arg.ID, arg.BusinessID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.AppVersion,
		&i.OsVersion,
		&i.LastPingAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDevicesByBusiness = `-- name: ListDevicesByBusiness :many
SELECT id, business_id, name, token_hash, token_prefix, app_version, os_version, last_ping_at, deactivated_at, created_at,
    COALESCE(
        deactivated_at IS NULL AND last_ping_at IS NOT NULL
        AND last_ping_at > now() - INTERVAL '5 minutes',
    false)::boolean AS online
FROM devices
WHERE business_id = $1
ORDER BY created_at DESC
`

type ListDevicesByBusinessRow struct {
	ID            uuid.UUID          `json:"id"`
	BusinessID    uuid.UUID          `json:"business_id"`
	Name          string             `json:"name"`
	TokenHash     string             `json:"token_hash"`
	TokenPrefix   string             `json:"token_prefix"`
	AppVersion    *string            `json:"app_version"`
	OsVersion     *string            `json:"os_version"`
	LastPingAt    pgtype.Timestamptz `json:"last_ping_at"`
	DeactivatedAt pgtype.Timestamptz `json:"deactivated_at"`
	CreatedAt     time.Time          `json:"created_at"`
	Online        bool               `json:"online"`
}

func (q *Queries) ListDevicesByBusiness(ctx context.Context, businessID uuid.UUID) ([]ListDevicesByBusinessRow, error) {
	rows, err := q.db.Query(ctx, listDevicesByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesByBusinessRow
	for rows.Next() {
		var i ListDevicesByBusinessRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.AppVersion,
			&i.OsVersion,
			&i.LastPingAt,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.Online,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceMeta = `-- name: UpdateDeviceMeta :exec
UPDATE devices
SET app_version = COALESCE($2, app_version), os_version = COALESCE($3, os_version)
WHERE id = $1
`

type UpdateDeviceMetaParams struct {
	ID         uuid.UUID `json:"id"`
	AppVersion *string   `json:"app_version"`
	OsVersion  *string   `json:"os_version"`
}

func (q *Queries) UpdateDeviceMeta(ctx context.Context, arg UpdateDeviceMetaParams) error {
	_, err := q.db.Exec(ctx, updateDeviceMeta, arg.ID, arg.AppVersion, arg.OsVersion)
	return err
}
