// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manage.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countAttempts = `-- name: CountAttempts :one
SELECT COUNT(*) AS total
FROM verification_attempts
WHERE
    ($1::uuid IS NULL OR business_id = $1::uuid)
    AND ($2::text IS NULL OR result = $2::text)
    AND ($3::text IS NULL OR submitted_trx_id = $3::text)
`

type CountAttemptsParams struct {
	BusinessID *uuid.UUID `json:"business_id"`
	Result     *string    `json:"result"`
	TrxID      *string    `json:"trx_id"`
}

func (q *Queries) CountAttempts(ctx context.Context, arg CountAttemptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAttempts, arg.BusinessID, arg.Result, arg.TrxID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countBusinesses = `-- name: CountBusinesses :one
SELECT COUNT(*) AS total FROM businesses
WHERE
    ($1::text IS NULL OR status = $1::text)
    AND (
        $2::text IS NULL
        OR name ILIKE '%' || $2::text || '%'
        OR owner_email ILIKE '%' || $2::text || '%'
    )
`

type CountBusinessesParams struct {
	Status *string `json:"status"`
	Search *string `json:"search"`
}

func (q *Queries) CountBusinesses(ctx context.Context, arg CountBusinessesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBusinesses, arg.Status, arg.Search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countDevices = `-- name: CountDevices :one
SELECT COUNT(*) AS total
FROM devices
WHERE ($1::uuid IS NULL OR business_id = $1::uuid)
`

func (q *Queries) CountDevices(ctx context.Context, businessID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDevices, businessID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countMessages = `-- name: CountMessages :one
SELECT COUNT(*) AS total
FROM raw_messages
WHERE
    ($1::uuid IS NULL OR business_id = $1::uuid)
    AND ($2::text IS NULL OR parse_status = $2::text)
`

type CountMessagesParams struct {
	BusinessID  *uuid.UUID `json:"business_id"`
	ParseStatus *string    `json:"parse_status"`
}

func (q *Queries) CountMessages(ctx context.Context, arg CountMessagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMessages, arg.BusinessID, arg.ParseStatus)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOrders = `-- name: CountOrders :one
SELECT COUNT(*) AS total
FROM orders
WHERE
    ($1::text IS NULL OR status = $1::text)
    AND ($2::uuid IS NULL OR business_id = $2::uuid)
`

type CountOrdersParams struct {
	Status     *string    `json:"status"`
	BusinessID *uuid.UUID `json:"business_id"`
}

func (q *Queries) CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders, arg.Status, arg.BusinessID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countProviders = `-- name: CountProviders :one
SELECT COUNT(*) AS total
FROM providers p
WHERE
    p.is_active = true
    AND (p.business_id IS NULL OR p.business_id = $1::uuid)
    AND ($2::text IS NULL OR p.direction = $2::text)
    AND ($3::text IS NULL OR p.match_mode = $3::text)
`

type CountProvidersParams struct {
	BusinessID *uuid.UUID `json:"business_id"`
	Direction  *string    `json:"direction"`
	MatchMode  *string    `json:"match_mode"`
}

func (q *Queries) CountProviders(ctx context.Context, arg CountProvidersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProviders, arg.BusinessID, arg.Direction, arg.MatchMode)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*) AS total
FROM transactions
WHERE
    ($1::uuid IS NULL OR business_id = $1::uuid)
    AND ($2::uuid IS NULL OR provider_id = $2::uuid)
    AND ($3::text IS NULL OR direction = $3::text)
`

type CountTransactionsParams struct {
	BusinessID *uuid.UUID `json:"business_id"`
	ProviderID *uuid.UUID `json:"provider_id"`
	Direction  *string    `json:"direction"`
}

func (q *Queries) CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions, arg.BusinessID, arg.ProviderID, arg.Direction)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const deactivateProviderGlobal = `-- name: DeactivateProviderGlobal :one
UPDATE providers
SET is_active = false, updated_at = now()
WHERE id = $1 AND is_active = true
RETURNING id, business_id, name, sender_id, sms_template, compiled_pattern, priority, is_active, created_at, updated_at, direction, match_mode, script
`

func (q *Queries) DeactivateProviderGlobal(ctx context.Context, id uuid.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, deactivateProviderGlobal, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.SenderID,
		&i.SmsTemplate,
		&i.CompiledPattern,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Direction,
		&i.MatchMode,
		&i.Script,
	)
	return i, err
}

const getApiKeyByID = `-- name: GetApiKeyByID :one
SELECT id, business_id, label, key_prefix, key_hash, last_used_at, revoked_at, created_at FROM api_keys
WHERE id = $1
`

func (q *Queries) GetApiKeyByID(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Label,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, business_id, name, token_hash, token_prefix, app_version, os_version, last_ping_at, deactivated_at, created_at FROM devices
WHERE id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.AppVersion,
		&i.OsVersion,
		&i.LastPingAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStudioStats = `-- name: GetStudioStats :one
SELECT
    (SELECT COUNT(*) FROM businesses) AS businesses_total,
    (
        SELECT COUNT(*)
        FROM devices
        WHERE COALESCE(
            deactivated_at IS NULL AND last_ping_at IS NOT NULL
            AND last_ping_at > now() - INTERVAL '5 minutes',
        false)::boolean
    ) AS devices_online,
    (SELECT COUNT(*) FROM transactions) AS transactions_total,
    (SELECT COUNT(*) FROM transactions WHERE created_at >= now() - INTERVAL '24 hours') AS transactions_today,
    (SELECT COUNT(*) FROM orders WHERE status = 'pending') AS orders_pending,
    (SELECT COUNT(*) FROM orders WHERE status = 'paid') AS orders_paid,
    (SELECT COUNT(*) FROM verification_attempts WHERE created_at >= now() - INTERVAL '24 hours') AS attempts_today,
    (SELECT COUNT(*) FROM raw_messages WHERE parse_status IN ('unmatched', 'error')) AS messages_unparsed
`

type GetStudioStatsRow struct {
	BusinessesTotal   int64 `json:"businesses_total"`
	DevicesOnline     int64 `json:"devices_online"`
	TransactionsTotal int64 `json:"transactions_total"`
	TransactionsToday int64 `json:"transactions_today"`
	OrdersPending     int64 `json:"orders_pending"`
	OrdersPaid        int64 `json:"orders_paid"`
	AttemptsToday     int64 `json:"attempts_today"`
	MessagesUnparsed  int64 `json:"messages_unparsed"`
}

func (q *Queries) GetStudioStats(ctx context.Context) (GetStudioStatsRow, error) {
	row := q.db.QueryRow(ctx, getStudioStats)
	var i GetStudioStatsRow
	err := row.Scan(
		&i.BusinessesTotal,
		&i.DevicesOnline,
		&i.TransactionsTotal,
		&i.TransactionsToday,
		&i.OrdersPending,
		&i.OrdersPaid,
		&i.AttemptsToday,
		&i.MessagesUnparsed,
	)
	return i, err
}

const listAttemptsPaged = `-- name: ListAttemptsPaged :many
SELECT va.id, va.business_id, va.order_id, va.submitted_trx_id, va.result, va.matched_transaction_id, va.submitted_amount, va.balance_consistent, va.source_ip, va.created_at, b.name AS business_name
FROM verification_attempts va
JOIN businesses b ON b.id = va.business_id
WHERE
    ($3::uuid IS NULL OR va.business_id = $3::uuid)
    AND ($4::text IS NULL OR va.result = $4::text)
    AND ($5::text IS NULL OR va.submitted_trx_id = $5::text)
ORDER BY va.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAttemptsPagedParams struct {
	Limit      int32      `json:"limit"`
	Offset     int32      `json:"offset"`
	BusinessID *uuid.UUID `json:"business_id"`
	Result     *string    `json:"result"`
	TrxID      *string    `json:"trx_id"`
}

type ListAttemptsPagedRow struct {
	ID                   uuid.UUID        `json:"id"`
	BusinessID           uuid.UUID        `json:"business_id"`
	OrderID              *uuid.UUID       `json:"order_id"`
	SubmittedTrxID       string           `json:"submitted_trx_id"`
	Result               string           `json:"result"`
	MatchedTransactionID *uuid.UUID       `json:"matched_transaction_id"`
	SubmittedAmount      *decimal.Decimal `json:"submitted_amount"`
	BalanceConsistent    *bool            `json:"balance_consistent"`
	SourceIp             *netip.Addr      `json:"source_ip"`
	CreatedAt            time.Time        `json:"created_at"`
	BusinessName         string           `json:"business_name"`
}

func (q *Queries) ListAttemptsPaged(ctx context.Context, arg ListAttemptsPagedParams) ([]ListAttemptsPagedRow, error) {
	rows, err := q.db.Query(ctx, listAttemptsPaged,
		arg.Limit,
		arg.Offset,
		arg.BusinessID,
		arg.Result,
		arg.TrxID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttemptsPagedRow
	for rows.Next() {
		var i ListAttemptsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.OrderID,
			&i.SubmittedTrxID,
			&i.Result,
			&i.MatchedTransactionID,
			&i.SubmittedAmount,
			&i.BalanceConsistent,
			&i.SourceIp,
			&i.CreatedAt,
			&i.BusinessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinessesPaged = `-- name: ListBusinessesPaged :many
SELECT id, name, owner_email, status, created_at, updated_at FROM businesses
WHERE
    ($3::text IS NULL OR status = $3::text)
    AND (
        $4::text IS NULL
        OR name ILIKE '%' || $4::text || '%'
        OR owner_email ILIKE '%' || $4::text || '%'
    )
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBusinessesPagedParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Status *string `json:"status"`
	Search *string `json:"search"`
}

func (q *Queries) ListBusinessesPaged(ctx context.Context, arg ListBusinessesPagedParams) ([]Business, error) {
	rows, err := q.db.Query(ctx, listBusinessesPaged,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Business
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerEmail,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesPaged = `-- name: ListDevicesPaged :many
SELECT d.id, d.business_id, d.name, d.token_hash, d.token_prefix, d.app_version, d.os_version, d.last_ping_at, d.deactivated_at, d.created_at,
    COALESCE(
        d.deactivated_at IS NULL AND d.last_ping_at IS NOT NULL
        AND d.last_ping_at > now() - INTERVAL '5 minutes',
    false)::boolean AS online,
    b.name AS business_name
FROM devices d
JOIN businesses b ON b.id = d.business_id
WHERE ($3::uuid IS NULL OR d.business_id = $3::uuid)
ORDER BY d.created_at DESC
LIMIT $1 OFFSET $2
`

type ListDevicesPagedParams struct {
	Limit      int32      `json:"limit"`
	Offset     int32      `json:"offset"`
	BusinessID *uuid.UUID `json:"business_id"`
}

type ListDevicesPagedRow struct {
	ID            uuid.UUID          `json:"id"`
	BusinessID    uuid.UUID          `json:"business_id"`
	Name          string             `json:"name"`
	TokenHash     string             `json:"token_hash"`
	TokenPrefix   string             `json:"token_prefix"`
	AppVersion    *string            `json:"app_version"`
	OsVersion     *string            `json:"os_version"`
	LastPingAt    pgtype.Timestamptz `json:"last_ping_at"`
	DeactivatedAt pgtype.Timestamptz `json:"deactivated_at"`
	CreatedAt     time.Time          `json:"created_at"`
	Online        bool               `json:"online"`
	BusinessName  string             `json:"business_name"`
}

func (q *Queries) ListDevicesPaged(ctx context.Context, arg ListDevicesPagedParams) ([]ListDevicesPagedRow, error) {
	rows, err := q.db.Query(ctx, listDevicesPaged, arg.Limit, arg.Offset, arg.BusinessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesPagedRow
	for rows.Next() {
		var i ListDevicesPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.AppVersion,
			&i.OsVersion,
			&i.LastPingAt,
			&i.DeactivatedAt,
			&i.CreatedAt,
			&i.Online,
			&i.BusinessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesPaged = `-- name: ListMessagesPaged :many
SELECT rm.id, rm.client_msg_id, rm.device_id, rm.business_id, rm.sender_id, rm.body, rm.device_received_at, rm.ingested_at, rm.parse_status, rm.error_code, rm.error_detail, rm.provider_id, rm.matched_pattern, rm.transaction_id, b.name AS business_name
FROM raw_messages rm
JOIN businesses b ON b.id = rm.business_id
WHERE
    ($3::uuid IS NULL OR rm.business_id = $3::uuid)
    AND ($4::text IS NULL OR rm.parse_status = $4::text)
ORDER BY rm.ingested_at DESC
LIMIT $1 OFFSET $2
`

type ListMessagesPagedParams struct {
	Limit       int32      `json:"limit"`
	Offset      int32      `json:"offset"`
	BusinessID  *uuid.UUID `json:"business_id"`
	ParseStatus *string    `json:"parse_status"`
}

type ListMessagesPagedRow struct {
	ID               uuid.UUID          `json:"id"`
	ClientMsgID      uuid.UUID          `json:"client_msg_id"`
	DeviceID         uuid.UUID          `json:"device_id"`
	BusinessID       uuid.UUID          `json:"business_id"`
	SenderID         *string            `json:"sender_id"`
	Body             string             `json:"body"`
	DeviceReceivedAt pgtype.Timestamptz `json:"device_received_at"`
	IngestedAt       time.Time          `json:"ingested_at"`
	ParseStatus      string             `json:"parse_status"`
	ErrorCode        *string            `json:"error_code"`
	ErrorDetail      *string            `json:"error_detail"`
	ProviderID       *uuid.UUID         `json:"provider_id"`
	MatchedPattern   *string            `json:"matched_pattern"`
	TransactionID    *uuid.UUID         `json:"transaction_id"`
	BusinessName     string             `json:"business_name"`
}

func (q *Queries) ListMessagesPaged(ctx context.Context, arg ListMessagesPagedParams) ([]ListMessagesPagedRow, error) {
	rows, err := q.db.Query(ctx, listMessagesPaged,
		arg.Limit,
		arg.Offset,
		arg.BusinessID,
		arg.ParseStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesPagedRow
	for rows.Next() {
		var i ListMessagesPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientMsgID,
			&i.DeviceID,
			&i.BusinessID,
			&i.SenderID,
			&i.Body,
			&i.DeviceReceivedAt,
			&i.IngestedAt,
			&i.ParseStatus,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.ProviderID,
			&i.MatchedPattern,
			&i.TransactionID,
			&i.BusinessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersPaged = `-- name: ListOrdersPaged :many
SELECT o.id, o.business_id, o.external_order_id, o.expected_amount, o.status, o.matched_transaction_id, o.expires_at, o.paid_at, o.metadata, o.created_at, o.updated_at, b.name AS business_name
FROM orders o
JOIN businesses b ON b.id = o.business_id
WHERE
    ($3::text IS NULL OR o.status = $3::text)
    AND ($4::uuid IS NULL OR o.business_id = $4::uuid)
ORDER BY o.created_at DESC
LIMIT $1 OFFSET $2
`

type ListOrdersPagedParams struct {
	Limit      int32      `json:"limit"`
	Offset     int32      `json:"offset"`
	Status     *string    `json:"status"`
	BusinessID *uuid.UUID `json:"business_id"`
}

type ListOrdersPagedRow struct {
	ID                   uuid.UUID          `json:"id"`
	BusinessID           uuid.UUID          `json:"business_id"`
	ExternalOrderID      string             `json:"external_order_id"`
	ExpectedAmount       decimal.Decimal    `json:"expected_amount"`
	Status               string             `json:"status"`
	MatchedTransactionID *uuid.UUID         `json:"matched_transaction_id"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	PaidAt               pgtype.Timestamptz `json:"paid_at"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	BusinessName         string             `json:"business_name"`
}

func (q *Queries) ListOrdersPaged(ctx context.Context, arg ListOrdersPagedParams) ([]ListOrdersPagedRow, error) {
	rows, err := q.db.Query(ctx, listOrdersPaged,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.BusinessID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersPagedRow
	for rows.Next() {
		var i ListOrdersPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ExternalOrderID,
			&i.ExpectedAmount,
			&i.Status,
			&i.MatchedTransactionID,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BusinessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersPaged = `-- name: ListProvidersPaged :many
SELECT p.id, p.business_id, p.name, p.sender_id, p.sms_template, p.compiled_pattern, p.priority, p.is_active, p.created_at, p.updated_at, p.direction, p.match_mode, p.script, b.name AS business_name
FROM providers p
LEFT JOIN businesses b ON b.id = p.business_id
WHERE
    p.is_active = true
    AND (p.business_id IS NULL OR p.business_id = $3::uuid)
    AND ($4::text IS NULL OR p.direction = $4::text)
    AND ($5::text IS NULL OR p.match_mode = $5::text)
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProvidersPagedParams struct {
	Limit      int32      `json:"limit"`
	Offset     int32      `json:"offset"`
	BusinessID *uuid.UUID `json:"business_id"`
	Direction  *string    `json:"direction"`
	MatchMode  *string    `json:"match_mode"`
}

type ListProvidersPagedRow struct {
	ID              uuid.UUID  `json:"id"`
	BusinessID      *uuid.UUID `json:"business_id"`
	Name            string     `json:"name"`
	SenderID        *string    `json:"sender_id"`
	SmsTemplate     string     `json:"sms_template"`
	CompiledPattern string     `json:"compiled_pattern"`
	Priority        int32      `json:"priority"`
	IsActive        bool       `json:"is_active"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	Direction       string     `json:"direction"`
	MatchMode       string     `json:"match_mode"`
	Script          *string    `json:"script"`
	BusinessName    *string    `json:"business_name"`
}

func (q *Queries) ListProvidersPaged(ctx context.Context, arg ListProvidersPagedParams) ([]ListProvidersPagedRow, error) {
	rows, err := q.db.Query(ctx, listProvidersPaged,
		arg.Limit,
		arg.Offset,
		arg.BusinessID,
		arg.Direction,
		arg.MatchMode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProvidersPagedRow
	for rows.Next() {
		var i ListProvidersPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.SenderID,
			&i.SmsTemplate,
			&i.CompiledPattern,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Direction,
			&i.MatchMode,
			&i.Script,
			&i.BusinessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsPaged = `-- name: ListTransactionsPaged :many
SELECT t.id, t.provider_id, t.trx_id, t.business_id, t.device_id, t.raw_message_id, t.amount, t.sender_msisdn, t.balance_after, t.received_at, t.created_at, t.direction, t.effective_amount, t.meta, b.name AS business_name, p.name AS provider_name
FROM transactions t
JOIN businesses b ON b.id = t.business_id
JOIN providers p ON p.id = t.provider_id
WHERE
    ($3::uuid IS NULL OR t.business_id = $3::uuid)
    AND ($4::uuid IS NULL OR t.provider_id = $4::uuid)
    AND ($5::text IS NULL OR t.direction = $5::text)
ORDER BY t.created_at DESC
LIMIT $1 OFFSET $2
`

type ListTransactionsPagedParams struct {
	Limit      int32      `json:"limit"`
	Offset     int32      `json:"offset"`
	BusinessID *uuid.UUID `json:"business_id"`
	ProviderID *uuid.UUID `json:"provider_id"`
	Direction  *string    `json:"direction"`
}

type ListTransactionsPagedRow struct {
	ID              uuid.UUID        `json:"id"`
	ProviderID      uuid.UUID        `json:"provider_id"`
	TrxID           string           `json:"trx_id"`
	BusinessID      uuid.UUID        `json:"business_id"`
	DeviceID        uuid.UUID        `json:"device_id"`
	RawMessageID    uuid.UUID        `json:"raw_message_id"`
	Amount          decimal.Decimal  `json:"amount"`
	SenderMsisdn    *string          `json:"sender_msisdn"`
	BalanceAfter    *decimal.Decimal `json:"balance_after"`
	ReceivedAt      time.Time        `json:"received_at"`
	CreatedAt       time.Time        `json:"created_at"`
	Direction       string           `json:"direction"`
	EffectiveAmount *decimal.Decimal `json:"effective_amount"`
	Meta            []byte           `json:"meta"`
	BusinessName    string           `json:"business_name"`
	ProviderName    string           `json:"provider_name"`
}

func (q *Queries) ListTransactionsPaged(ctx context.Context, arg ListTransactionsPagedParams) ([]ListTransactionsPagedRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsPaged,
		arg.Limit,
		arg.Offset,
		arg.BusinessID,
		arg.ProviderID,
		arg.Direction,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsPagedRow
	for rows.Next() {
		var i ListTransactionsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.TrxID,
			&i.BusinessID,
			&i.DeviceID,
			&i.RawMessageID,
			&i.Amount,
			&i.SenderMsisdn,
			&i.BalanceAfter,
			&i.ReceivedAt,
			&i.CreatedAt,
			&i.Direction,
			&i.EffectiveAmount,
			&i.Meta,
			&i.BusinessName,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderTemplateGlobal = `-- name: UpdateProviderTemplateGlobal :one
UPDATE providers
SET sms_template = $2, compiled_pattern = $3, direction = $4, script = $5, match_mode = $6, updated_at = now()
WHERE id = $1
RETURNING id, business_id, name, sender_id, sms_template, compiled_pattern, priority, is_active, created_at, updated_at, direction, match_mode, script
`

type UpdateProviderTemplateGlobalParams struct {
	ID              uuid.UUID `json:"id"`
	SmsTemplate     string    `json:"sms_template"`
	CompiledPattern string    `json:"compiled_pattern"`
	Direction       string    `json:"direction"`
	Script          *string   `json:"script"`
	MatchMode       string    `json:"match_mode"`
}

func (q *Queries) UpdateProviderTemplateGlobal(ctx context.Context, arg UpdateProviderTemplateGlobalParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProviderTemplateGlobal,
		arg.ID,
		arg.SmsTemplate,
		arg.CompiledPattern,
		arg.Direction,
		arg.Script,
		arg.MatchMode,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.SenderID,
		&i.SmsTemplate,
		&i.CompiledPattern,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Direction,
		&i.MatchMode,
		&i.Script,
	)
	return i, err
}
