// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	BusinessID uuid.UUID          `json:"business_id"`
	Label      string             `json:"label"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyHash    string             `json:"key_hash"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type BalanceCalibration struct {
	ID           uuid.UUID       `json:"id"`
	BusinessID   uuid.UUID       `json:"business_id"`
	DeviceID     uuid.UUID       `json:"device_id"`
	ProviderID   uuid.UUID       `json:"provider_id"`
	Balance      decimal.Decimal `json:"balance"`
	Note         *string         `json:"note"`
	CalibratedAt time.Time       `json:"calibrated_at"`
	CreatedAt    time.Time       `json:"created_at"`
}

type Business struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	OwnerEmail string    `json:"owner_email"`
	Status     string    `json:"status"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Device struct {
	ID            uuid.UUID          `json:"id"`
	BusinessID    uuid.UUID          `json:"business_id"`
	Name          string             `json:"name"`
	TokenHash     string             `json:"token_hash"`
	TokenPrefix   string             `json:"token_prefix"`
	AppVersion    *string            `json:"app_version"`
	OsVersion     *string            `json:"os_version"`
	LastPingAt    pgtype.Timestamptz `json:"last_ping_at"`
	DeactivatedAt pgtype.Timestamptz `json:"deactivated_at"`
	CreatedAt     time.Time          `json:"created_at"`
}

type Order struct {
	ID                   uuid.UUID          `json:"id"`
	BusinessID           uuid.UUID          `json:"business_id"`
	ExternalOrderID      string             `json:"external_order_id"`
	ExpectedAmount       decimal.Decimal    `json:"expected_amount"`
	Status               string             `json:"status"`
	MatchedTransactionID *uuid.UUID         `json:"matched_transaction_id"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	PaidAt               pgtype.Timestamptz `json:"paid_at"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type Provider struct {
	ID              uuid.UUID  `json:"id"`
	BusinessID      *uuid.UUID `json:"business_id"`
	Name            string     `json:"name"`
	SenderID        *string    `json:"sender_id"`
	SmsTemplate     string     `json:"sms_template"`
	CompiledPattern string     `json:"compiled_pattern"`
	Priority        int32      `json:"priority"`
	IsActive        bool       `json:"is_active"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	Direction       string     `json:"direction"`
	MatchMode       string     `json:"match_mode"`
	Script          *string    `json:"script"`
}

type RawMessage struct {
	ID               uuid.UUID          `json:"id"`
	ClientMsgID      uuid.UUID          `json:"client_msg_id"`
	DeviceID         uuid.UUID          `json:"device_id"`
	BusinessID       uuid.UUID          `json:"business_id"`
	SenderID         *string            `json:"sender_id"`
	Body             string             `json:"body"`
	DeviceReceivedAt pgtype.Timestamptz `json:"device_received_at"`
	IngestedAt       time.Time          `json:"ingested_at"`
	ParseStatus      string             `json:"parse_status"`
	ErrorCode        *string            `json:"error_code"`
	ErrorDetail      *string            `json:"error_detail"`
	ProviderID       *uuid.UUID         `json:"provider_id"`
	MatchedPattern   *string            `json:"matched_pattern"`
	TransactionID    *uuid.UUID         `json:"transaction_id"`
}

type Transaction struct {
	ID              uuid.UUID        `json:"id"`
	ProviderID      uuid.UUID        `json:"provider_id"`
	TrxID           string           `json:"trx_id"`
	BusinessID      uuid.UUID        `json:"business_id"`
	DeviceID        uuid.UUID        `json:"device_id"`
	RawMessageID    uuid.UUID        `json:"raw_message_id"`
	Amount          decimal.Decimal  `json:"amount"`
	SenderMsisdn    *string          `json:"sender_msisdn"`
	BalanceAfter    *decimal.Decimal `json:"balance_after"`
	ReceivedAt      time.Time        `json:"received_at"`
	CreatedAt       time.Time        `json:"created_at"`
	Direction       string           `json:"direction"`
	EffectiveAmount *decimal.Decimal `json:"effective_amount"`
	Meta            []byte           `json:"meta"`
}

type VerificationAttempt struct {
	ID                   uuid.UUID        `json:"id"`
	BusinessID           uuid.UUID        `json:"business_id"`
	OrderID              *uuid.UUID       `json:"order_id"`
	SubmittedTrxID       string           `json:"submitted_trx_id"`
	Result               string           `json:"result"`
	MatchedTransactionID *uuid.UUID       `json:"matched_transaction_id"`
	SubmittedAmount      *decimal.Decimal `json:"submitted_amount"`
	BalanceConsistent    *bool            `json:"balance_consistent"`
	SourceIp             *netip.Addr      `json:"source_ip"`
	CreatedAt            time.Time        `json:"created_at"`
}
