// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders
SET status = 'cancelled', updated_at = now()
WHERE id = $1 AND business_id = $2 AND status = 'pending'
RETURNING id, business_id, external_order_id, expected_amount, status, matched_transaction_id, expires_at, paid_at, metadata, created_at, updated_at
`

type CancelOrderParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, cancelOrder, arg.ID, arg.BusinessID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ExternalOrderID,
		&i.ExpectedAmount,
		&i.Status,
		&i.MatchedTransactionID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimTransactionForOrder = `-- name: ClaimTransactionForOrder :one
UPDATE orders
SET matched_transaction_id = $2,
    status = 'paid',
    paid_at = now(),
    updated_at = now()
WHERE id = $1
  AND business_id = $3
  AND status = 'pending'
  AND matched_transaction_id IS NULL
RETURNING id, business_id, external_order_id, expected_amount, status, matched_transaction_id, expires_at, paid_at, metadata, created_at, updated_at
`

type ClaimTransactionForOrderParams struct {
	ID                   uuid.UUID  `json:"id"`
	MatchedTransactionID *uuid.UUID `json:"matched_transaction_id"`
	BusinessID           uuid.UUID  `json:"business_id"`
}

func (q *Queries) ClaimTransactionForOrder(ctx context.Context, arg ClaimTransactionForOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, claimTransactionForOrder, arg.ID, arg.MatchedTransactionID, arg.BusinessID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ExternalOrderID,
		&i.ExpectedAmount,
		&i.Status,
		&i.MatchedTransactionID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireStaleOrders = `-- name: ExpireStaleOrders :execrows
UPDATE orders
SET status = 'expired', updated_at = now()
WHERE status = 'pending'
  AND expires_at IS NOT NULL
  AND expires_at < now()
`

func (q *Queries) ExpireStaleOrders(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireStaleOrders)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrder = `-- name: GetOrder :one
SELECT id, business_id, external_order_id, expected_amount, status, matched_transaction_id, expires_at, paid_at, metadata, created_at, updated_at FROM orders
WHERE id = $1 AND business_id = $2
`

type GetOrderParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.ID, arg.BusinessID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ExternalOrderID,
		&i.ExpectedAmount,
		&i.Status,
		&i.MatchedTransactionID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByExternalID = `-- name: GetOrderByExternalID :one
SELECT id, business_id, external_order_id, expected_amount, status, matched_transaction_id, expires_at, paid_at, metadata, created_at, updated_at FROM orders
WHERE business_id = $1 AND external_order_id = $2
`

type GetOrderByExternalIDParams struct {
	BusinessID      uuid.UUID `json:"business_id"`
	ExternalOrderID string    `json:"external_order_id"`
}

func (q *Queries) GetOrderByExternalID(ctx context.Context, arg GetOrderByExternalIDParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByExternalID, arg.BusinessID, arg.ExternalOrderID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ExternalOrderID,
		&i.ExpectedAmount,
		&i.Status,
		&i.MatchedTransactionID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (business_id, external_order_id, expected_amount, expires_at, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, business_id, external_order_id, expected_amount, status, matched_transaction_id, expires_at, paid_at, metadata, created_at, updated_at
`

type InsertOrderParams struct {
	BusinessID      uuid.UUID          `json:"business_id"`
	ExternalOrderID string             `json:"external_order_id"`
	ExpectedAmount  decimal.Decimal    `json:"expected_amount"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	Metadata        []byte             `json:"metadata"`
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.BusinessID,
		arg.ExternalOrderID,
		arg.ExpectedAmount,
		arg.ExpiresAt,
		arg.Metadata,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ExternalOrderID,
		&i.ExpectedAmount,
		&i.Status,
		&i.MatchedTransactionID,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrdersByBusiness = `-- name: ListOrdersByBusiness :many
SELECT id, business_id, external_order_id, expected_amount, status, matched_transaction_id, expires_at, paid_at, metadata, created_at, updated_at FROM orders
WHERE business_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByBusinessParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListOrdersByBusiness(ctx context.Context, arg ListOrdersByBusinessParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByBusiness, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ExternalOrderID,
			&i.ExpectedAmount,
			&i.Status,
			&i.MatchedTransactionID,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
