// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (business_id, name, sender_id, sms_template, compiled_pattern, priority, direction, match_mode, script)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, business_id, name, sender_id, sms_template, compiled_pattern, priority, is_active, created_at, updated_at, direction, match_mode, script
`

type CreateProviderParams struct {
	BusinessID      *uuid.UUID `json:"business_id"`
	Name            string     `json:"name"`
	SenderID        *string    `json:"sender_id"`
	SmsTemplate     string     `json:"sms_template"`
	CompiledPattern string     `json:"compiled_pattern"`
	Priority        int32      `json:"priority"`
	Direction       string     `json:"direction"`
	MatchMode       string     `json:"match_mode"`
	Script          *string    `json:"script"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.BusinessID,
		arg.Name,
		arg.SenderID,
		arg.SmsTemplate,
		arg.CompiledPattern,
		arg.Priority,
		arg.Direction,
		arg.MatchMode,
		arg.Script,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.SenderID,
		&i.SmsTemplate,
		&i.CompiledPattern,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Direction,
		&i.MatchMode,
		&i.Script,
	)
	return i, err
}

const deactivateProvider = `-- name: DeactivateProvider :one
UPDATE providers
SET is_active = false, updated_at = now()
WHERE id = $1 AND business_id = $2
RETURNING id, business_id, name, sender_id, sms_template, compiled_pattern, priority, is_active, created_at, updated_at, direction, match_mode, script
`

type DeactivateProviderParams struct {
	ID         uuid.UUID  `json:"id"`
	BusinessID *uuid.UUID `json:"business_id"`
}

func (q *Queries) DeactivateProvider(ctx context.Context, arg DeactivateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, deactivateProvider, arg.ID, arg.BusinessID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.SenderID,
		&i.SmsTemplate,
		&i.CompiledPattern,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Direction,
		&i.MatchMode,
		&i.Script,
	)
	return i, err
}

const getGlobalProviderByName = `-- name: GetGlobalProviderByName :one
SELECT id, business_id, name, sender_id, sms_template, compiled_pattern, priority, is_active, created_at, updated_at, direction, match_mode, script FROM providers
WHERE business_id IS NULL AND name = $1
`

func (q *Queries) GetGlobalProviderByName(ctx context.Context, name string) (Provider, error) {
	row := q.db.QueryRow(ctx, getGlobalProviderByName, name)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.SenderID,
		&i.SmsTemplate,
		&i.CompiledPattern,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Direction,
		&i.MatchMode,
		&i.Script,
	)
	return i, err
}

const getProvider = `-- name: GetProvider :one
SELECT id, business_id, name, sender_id, sms_template, compiled_pattern, priority, is_active, created_at, updated_at, direction, match_mode, script FROM providers
WHERE id = $1
`

func (q *Queries) GetProvider(ctx context.Context, id uuid.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.SenderID,
		&i.SmsTemplate,
		&i.CompiledPattern,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Direction,
		&i.MatchMode,
		&i.Script,
	)
	return i, err
}

const listActiveProvidersForMatching = `-- name: ListActiveProvidersForMatching :many
SELECT id, business_id, name, sender_id, sms_template, compiled_pattern, priority, is_active, created_at, updated_at, direction, match_mode, script FROM providers
WHERE is_active = true
  AND (business_id IS NULL OR business_id = $1)
ORDER BY priority ASC, business_id IS NULL ASC, created_at ASC
`

func (q *Queries) ListActiveProvidersForMatching(ctx context.Context, businessID *uuid.UUID) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listActiveProvidersForMatching, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.SenderID,
			&i.SmsTemplate,
			&i.CompiledPattern,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Direction,
			&i.MatchMode,
			&i.Script,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersForBusiness = `-- name: ListProvidersForBusiness :many
SELECT id, business_id, name, sender_id, sms_template, compiled_pattern, priority, is_active, created_at, updated_at, direction, match_mode, script FROM providers
WHERE business_id IS NULL OR business_id = $1
ORDER BY priority ASC, created_at ASC
`

func (q *Queries) ListProvidersForBusiness(ctx context.Context, businessID *uuid.UUID) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProvidersForBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.SenderID,
			&i.SmsTemplate,
			&i.CompiledPattern,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Direction,
			&i.MatchMode,
			&i.Script,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProviderPriority = `-- name: SetProviderPriority :one
UPDATE providers
SET priority = $2, updated_at = now()
WHERE id = $1 AND business_id = $3
RETURNING id, business_id, name, sender_id, sms_template, compiled_pattern, priority, is_active, created_at, updated_at, direction, match_mode, script
`

type SetProviderPriorityParams struct {
	ID         uuid.UUID  `json:"id"`
	Priority   int32      `json:"priority"`
	BusinessID *uuid.UUID `json:"business_id"`
}

func (q *Queries) SetProviderPriority(ctx context.Context, arg SetProviderPriorityParams) (Provider, error) {
	row := q.db.QueryRow(ctx, setProviderPriority, arg.ID, arg.Priority, arg.BusinessID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.SenderID,
		&i.SmsTemplate,
		&i.CompiledPattern,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Direction,
		&i.MatchMode,
		&i.Script,
	)
	return i, err
}

const updateProviderTemplate = `-- name: UpdateProviderTemplate :one
UPDATE providers
SET sms_template = $1, compiled_pattern = $2, direction = $3, script = $4, match_mode = $5, updated_at = now()
WHERE id = $6 AND business_id = $7
RETURNING id, business_id, name, sender_id, sms_template, compiled_pattern, priority, is_active, created_at, updated_at, direction, match_mode, script
`

type UpdateProviderTemplateParams struct {
	SmsTemplate     string     `json:"sms_template"`
	CompiledPattern string     `json:"compiled_pattern"`
	Direction       string     `json:"direction"`
	Script          *string    `json:"script"`
	MatchMode       string     `json:"match_mode"`
	ID              uuid.UUID  `json:"id"`
	BusinessID      *uuid.UUID `json:"business_id"`
}

func (q *Queries) UpdateProviderTemplate(ctx context.Context, arg UpdateProviderTemplateParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProviderTemplate,
		arg.SmsTemplate,
		arg.CompiledPattern,
		arg.Direction,
		arg.Script,
		arg.MatchMode,
		arg.ID,
		arg.BusinessID,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.SenderID,
		&i.SmsTemplate,
		&i.CompiledPattern,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Direction,
		&i.MatchMode,
		&i.Script,
	)
	return i, err
}
