// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Querier interface {
	CancelOrder(ctx context.Context, arg CancelOrderParams) (Order, error)
	ClaimTransactionForOrder(ctx context.Context, arg ClaimTransactionForOrderParams) (Order, error)
	CountRawMessagesByStatus(ctx context.Context, businessID uuid.UUID) ([]CountRawMessagesByStatusRow, error)
	CountRecentAttemptsByBusiness(ctx context.Context, arg CountRecentAttemptsByBusinessParams) (int64, error)
	CountRecentAttemptsByIP(ctx context.Context, arg CountRecentAttemptsByIPParams) (int64, error)
	CountTransactionsAfter(ctx context.Context, arg CountTransactionsAfterParams) (int64, error)
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error)
	CreateBalanceCalibration(ctx context.Context, arg CreateBalanceCalibrationParams) (BalanceCalibration, error)
	CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	DeactivateDevice(ctx context.Context, arg DeactivateDeviceParams) (Device, error)
	DeactivateProvider(ctx context.Context, arg DeactivateProviderParams) (Provider, error)
	DeviceHeartbeat(ctx context.Context, id uuid.UUID) error
	ExpireStaleOrders(ctx context.Context) (int64, error)
	FindTransactionByTrxIDForBusiness(ctx context.Context, arg FindTransactionByTrxIDForBusinessParams) (Transaction, error)
	GetApiKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error)
	GetBusiness(ctx context.Context, id uuid.UUID) (Business, error)
	GetBusinessByEmail(ctx context.Context, ownerEmail string) (Business, error)
	GetDeviceByTokenPrefix(ctx context.Context, tokenPrefix string) ([]Device, error)
	GetDeviceForBusiness(ctx context.Context, arg GetDeviceForBusinessParams) (Device, error)
	GetGlobalProviderByName(ctx context.Context, name string) (Provider, error)
	GetLatestBalancePoint(ctx context.Context, arg GetLatestBalancePointParams) (GetLatestBalancePointRow, error)
	GetLatestCalibrationAfter(ctx context.Context, arg GetLatestCalibrationAfterParams) (decimal.Decimal, error)
	GetOrder(ctx context.Context, arg GetOrderParams) (Order, error)
	GetOrderByExternalID(ctx context.Context, arg GetOrderByExternalIDParams) (Order, error)
	GetPreviousBalance(ctx context.Context, arg GetPreviousBalanceParams) (*decimal.Decimal, error)
	GetProvider(ctx context.Context, id uuid.UUID) (Provider, error)
	GetRawMessage(ctx context.Context, id uuid.UUID) (RawMessage, error)
	GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error)
	GetTransactionByProviderAndTrxID(ctx context.Context, arg GetTransactionByProviderAndTrxIDParams) (Transaction, error)
	InsertOrder(ctx context.Context, arg InsertOrderParams) (Order, error)
	InsertRawMessage(ctx context.Context, arg InsertRawMessageParams) (RawMessage, error)
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error)
	InsertVerificationAttempt(ctx context.Context, arg InsertVerificationAttemptParams) error
	ListActiveProvidersForMatching(ctx context.Context, businessID *uuid.UUID) ([]Provider, error)
	ListApiKeysByBusiness(ctx context.Context, businessID uuid.UUID) ([]ApiKey, error)
	ListApiKeysByPrefix(ctx context.Context, keyPrefix string) ([]ListApiKeysByPrefixRow, error)
	ListAttemptsByTrxID(ctx context.Context, arg ListAttemptsByTrxIDParams) ([]VerificationAttempt, error)
	ListBusinesses(ctx context.Context) ([]Business, error)
	ListDevicesByBusiness(ctx context.Context, businessID uuid.UUID) ([]ListDevicesByBusinessRow, error)
	ListOrdersByBusiness(ctx context.Context, arg ListOrdersByBusinessParams) ([]Order, error)
	ListPendingRawMessages(ctx context.Context, limit int32) ([]RawMessage, error)
	ListProblemMessagesByBusiness(ctx context.Context, arg ListProblemMessagesByBusinessParams) ([]RawMessage, error)
	ListProvidersForBusiness(ctx context.Context, businessID *uuid.UUID) ([]Provider, error)
	MarkRawMessageError(ctx context.Context, arg MarkRawMessageErrorParams) error
	MarkRawMessageParsed(ctx context.Context, arg MarkRawMessageParsedParams) error
	MarkRawMessageUnmatched(ctx context.Context, id uuid.UUID) error
	RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) (ApiKey, error)
	SetBusinessStatus(ctx context.Context, arg SetBusinessStatusParams) (Business, error)
	SetProviderPriority(ctx context.Context, arg SetProviderPriorityParams) (Provider, error)
	TouchApiKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateDeviceMeta(ctx context.Context, arg UpdateDeviceMetaParams) error
	UpdateProviderTemplate(ctx context.Context, arg UpdateProviderTemplateParams) (Provider, error)
}

var _ Querier = (*Queries)(nil)
