// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: raw_messages.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRawMessagesByStatus = `-- name: CountRawMessagesByStatus :many
SELECT parse_status, COUNT(*) AS message_count
FROM raw_messages
WHERE business_id = $1
GROUP BY parse_status
`

type CountRawMessagesByStatusRow struct {
	ParseStatus  string `json:"parse_status"`
	MessageCount int64  `json:"message_count"`
}

func (q *Queries) CountRawMessagesByStatus(ctx context.Context, businessID uuid.UUID) ([]CountRawMessagesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countRawMessagesByStatus, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRawMessagesByStatusRow
	for rows.Next() {
		var i CountRawMessagesByStatusRow
		if err := rows.Scan(&i.ParseStatus, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRawMessage = `-- name: GetRawMessage :one
SELECT id, client_msg_id, device_id, business_id, sender_id, body, device_received_at, ingested_at, parse_status, error_code, error_detail, provider_id, matched_pattern, transaction_id FROM raw_messages
WHERE id = $1
`

func (q *Queries) GetRawMessage(ctx context.Context, id uuid.UUID) (RawMessage, error) {
	row := q.db.QueryRow(ctx, getRawMessage, id)
	var i RawMessage
	err := row.Scan(
		&i.ID,
		&i.ClientMsgID,
		&i.DeviceID,
		&i.BusinessID,
		&i.SenderID,
		&i.Body,
		&i.DeviceReceivedAt,
		&i.IngestedAt,
		&i.ParseStatus,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.ProviderID,
		&i.MatchedPattern,
		&i.TransactionID,
	)
	return i, err
}

const insertRawMessage = `-- name: InsertRawMessage :one
INSERT INTO raw_messages (client_msg_id, device_id, business_id, sender_id, body, device_received_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (device_id, client_msg_id) DO NOTHING
RETURNING id, client_msg_id, device_id, business_id, sender_id, body, device_received_at, ingested_at, parse_status, error_code, error_detail, provider_id, matched_pattern, transaction_id
`

type InsertRawMessageParams struct {
	ClientMsgID      uuid.UUID          `json:"client_msg_id"`
	DeviceID         uuid.UUID          `json:"device_id"`
	BusinessID       uuid.UUID          `json:"business_id"`
	SenderID         *string            `json:"sender_id"`
	Body             string             `json:"body"`
	DeviceReceivedAt pgtype.Timestamptz `json:"device_received_at"`
}

func (q *Queries) InsertRawMessage(ctx context.Context, arg InsertRawMessageParams) (RawMessage, error) {
	row := q.db.QueryRow(ctx, insertRawMessage,
		arg.ClientMsgID,
		arg.DeviceID,
		arg.BusinessID,
		arg.SenderID,
		arg.Body,
		arg.DeviceReceivedAt,
	)
	var i RawMessage
	err := row.Scan(
		&i.ID,
		&i.ClientMsgID,
		&i.DeviceID,
		&i.BusinessID,
		&i.SenderID,
		&i.Body,
		&i.DeviceReceivedAt,
		&i.IngestedAt,
		&i.ParseStatus,
		&i.ErrorCode,
		&i.ErrorDetail,
		&i.ProviderID,
		&i.MatchedPattern,
		&i.TransactionID,
	)
	return i, err
}

const listPendingRawMessages = `-- name: ListPendingRawMessages :many
SELECT id, client_msg_id, device_id, business_id, sender_id, body, device_received_at, ingested_at, parse_status, error_code, error_detail, provider_id, matched_pattern, transaction_id FROM raw_messages
WHERE parse_status = 'pending'
ORDER BY ingested_at ASC
LIMIT $1
`

func (q *Queries) ListPendingRawMessages(ctx context.Context, limit int32) ([]RawMessage, error) {
	rows, err := q.db.Query(ctx, listPendingRawMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RawMessage
	for rows.Next() {
		var i RawMessage
		if err := rows.Scan(
			&i.ID,
			&i.ClientMsgID,
			&i.DeviceID,
			&i.BusinessID,
			&i.SenderID,
			&i.Body,
			&i.DeviceReceivedAt,
			&i.IngestedAt,
			&i.ParseStatus,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.ProviderID,
			&i.MatchedPattern,
			&i.TransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemMessagesByBusiness = `-- name: ListProblemMessagesByBusiness :many
SELECT id, client_msg_id, device_id, business_id, sender_id, body, device_received_at, ingested_at, parse_status, error_code, error_detail, provider_id, matched_pattern, transaction_id FROM raw_messages
WHERE business_id = $1 AND parse_status IN ('unmatched', 'error')
ORDER BY ingested_at DESC
LIMIT $2 OFFSET $3
`

type ListProblemMessagesByBusinessParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListProblemMessagesByBusiness(ctx context.Context, arg ListProblemMessagesByBusinessParams) ([]RawMessage, error) {
	rows, err := q.db.Query(ctx, listProblemMessagesByBusiness, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RawMessage
	for rows.Next() {
		var i RawMessage
		if err := rows.Scan(
			&i.ID,
			&i.ClientMsgID,
			&i.DeviceID,
			&i.BusinessID,
			&i.SenderID,
			&i.Body,
			&i.DeviceReceivedAt,
			&i.IngestedAt,
			&i.ParseStatus,
			&i.ErrorCode,
			&i.ErrorDetail,
			&i.ProviderID,
			&i.MatchedPattern,
			&i.TransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRawMessageError = `-- name: MarkRawMessageError :exec
UPDATE raw_messages
SET parse_status = 'error', error_code = $2, error_detail = $3
WHERE id = $1
`

type MarkRawMessageErrorParams struct {
	ID          uuid.UUID `json:"id"`
	ErrorCode   *string   `json:"error_code"`
	ErrorDetail *string   `json:"error_detail"`
}

func (q *Queries) MarkRawMessageError(ctx context.Context, arg MarkRawMessageErrorParams) error {
	_, err := q.db.Exec(ctx, markRawMessageError, arg.ID, arg.ErrorCode, arg.ErrorDetail)
	return err
}

const markRawMessageParsed = `-- name: MarkRawMessageParsed :exec
UPDATE raw_messages
SET parse_status = 'parsed', provider_id = $2, matched_pattern = $3, transaction_id = $4
WHERE id = $1
`

type MarkRawMessageParsedParams struct {
	ID             uuid.UUID  `json:"id"`
	ProviderID     *uuid.UUID `json:"provider_id"`
	MatchedPattern *string    `json:"matched_pattern"`
	TransactionID  *uuid.UUID `json:"transaction_id"`
}

func (q *Queries) MarkRawMessageParsed(ctx context.Context, arg MarkRawMessageParsedParams) error {
	_, err := q.db.Exec(ctx, markRawMessageParsed,
		arg.ID,
		arg.ProviderID,
		arg.MatchedPattern,
		arg.TransactionID,
	)
	return err
}

const markRawMessageUnmatched = `-- name: MarkRawMessageUnmatched :exec
UPDATE raw_messages
SET parse_status = 'unmatched'
WHERE id = $1
`

func (q *Queries) MarkRawMessageUnmatched(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRawMessageUnmatched, id)
	return err
}
