// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const findTransactionByTrxIDForBusiness = `-- name: FindTransactionByTrxIDForBusiness :one
SELECT id, provider_id, trx_id, business_id, device_id, raw_message_id, amount, sender_msisdn, balance_after, received_at, created_at FROM transactions
WHERE trx_id = $1 AND business_id = $2
ORDER BY received_at DESC
LIMIT 1
`

type FindTransactionByTrxIDForBusinessParams struct {
	TrxID      string    `json:"trx_id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) FindTransactionByTrxIDForBusiness(ctx context.Context, arg FindTransactionByTrxIDForBusinessParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, findTransactionByTrxIDForBusiness, arg.TrxID, arg.BusinessID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.TrxID,
		&i.BusinessID,
		&i.DeviceID,
		&i.RawMessageID,
		&i.Amount,
		&i.SenderMsisdn,
		&i.BalanceAfter,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPreviousBalance = `-- name: GetPreviousBalance :one
SELECT balance_after
FROM transactions
WHERE device_id = $1
  AND balance_after IS NOT NULL
  AND id <> $2
  AND received_at < $3
ORDER BY received_at DESC, created_at DESC
LIMIT 1
`

type GetPreviousBalanceParams struct {
	DeviceID   uuid.UUID `json:"device_id"`
	ID         uuid.UUID `json:"id"`
	ReceivedAt time.Time `json:"received_at"`
}

func (q *Queries) GetPreviousBalance(ctx context.Context, arg GetPreviousBalanceParams) (*decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getPreviousBalance, arg.DeviceID, arg.ID, arg.ReceivedAt)
	var balance_after *decimal.Decimal
	err := row.Scan(&balance_after)
	return balance_after, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, provider_id, trx_id, business_id, device_id, raw_message_id, amount, sender_msisdn, balance_after, received_at, created_at FROM transactions
WHERE id = $1 AND business_id = $2
`

type GetTransactionByIDParams struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, arg.ID, arg.BusinessID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.TrxID,
		&i.BusinessID,
		&i.DeviceID,
		&i.RawMessageID,
		&i.Amount,
		&i.SenderMsisdn,
		&i.BalanceAfter,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (provider_id, trx_id, business_id, device_id, raw_message_id, amount, sender_msisdn, balance_after)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (provider_id, trx_id) DO NOTHING
RETURNING id, provider_id, trx_id, business_id, device_id, raw_message_id, amount, sender_msisdn, balance_after, received_at, created_at
`

type InsertTransactionParams struct {
	ProviderID   uuid.UUID        `json:"provider_id"`
	TrxID        string           `json:"trx_id"`
	BusinessID   uuid.UUID        `json:"business_id"`
	DeviceID     uuid.UUID        `json:"device_id"`
	RawMessageID uuid.UUID        `json:"raw_message_id"`
	Amount       decimal.Decimal  `json:"amount"`
	SenderMsisdn *string          `json:"sender_msisdn"`
	BalanceAfter *decimal.Decimal `json:"balance_after"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.ProviderID,
		arg.TrxID,
		arg.BusinessID,
		arg.DeviceID,
		arg.RawMessageID,
		arg.Amount,
		arg.SenderMsisdn,
		arg.BalanceAfter,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.TrxID,
		&i.BusinessID,
		&i.DeviceID,
		&i.RawMessageID,
		&i.Amount,
		&i.SenderMsisdn,
		&i.BalanceAfter,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}
