// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_attempts.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countRecentAttemptsByBusiness = `-- name: CountRecentAttemptsByBusiness :one
SELECT COUNT(*) AS attempt_count
FROM verification_attempts
WHERE business_id = $1
  AND created_at > now() - ($2::int * INTERVAL '1 second')
`

type CountRecentAttemptsByBusinessParams struct {
	BusinessID    uuid.UUID `json:"business_id"`
	WindowSeconds int32     `json:"window_seconds"`
}

func (q *Queries) CountRecentAttemptsByBusiness(ctx context.Context, arg CountRecentAttemptsByBusinessParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentAttemptsByBusiness, arg.BusinessID, arg.WindowSeconds)
	var attempt_count int64
	err := row.Scan(&attempt_count)
	return attempt_count, err
}

const insertVerificationAttempt = `-- name: InsertVerificationAttempt :exec
INSERT INTO verification_attempts (
    business_id, order_id, submitted_trx_id, result,
    matched_transaction_id, submitted_amount, balance_consistent, source_ip
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertVerificationAttemptParams struct {
	BusinessID           uuid.UUID        `json:"business_id"`
	OrderID              *uuid.UUID       `json:"order_id"`
	SubmittedTrxID       string           `json:"submitted_trx_id"`
	Result               string           `json:"result"`
	MatchedTransactionID *uuid.UUID       `json:"matched_transaction_id"`
	SubmittedAmount      *decimal.Decimal `json:"submitted_amount"`
	BalanceConsistent    *bool            `json:"balance_consistent"`
	SourceIp             *netip.Addr      `json:"source_ip"`
}

func (q *Queries) InsertVerificationAttempt(ctx context.Context, arg InsertVerificationAttemptParams) error {
	_, err := q.db.Exec(ctx, insertVerificationAttempt,
		arg.BusinessID,
		arg.OrderID,
		arg.SubmittedTrxID,
		arg.Result,
		arg.MatchedTransactionID,
		arg.SubmittedAmount,
		arg.BalanceConsistent,
		arg.SourceIp,
	)
	return err
}

const listAttemptsByTrxID = `-- name: ListAttemptsByTrxID :many
SELECT id, business_id, order_id, submitted_trx_id, result, matched_transaction_id, submitted_amount, balance_consistent, source_ip, created_at FROM verification_attempts
WHERE business_id = $1 AND submitted_trx_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListAttemptsByTrxIDParams struct {
	BusinessID     uuid.UUID `json:"business_id"`
	SubmittedTrxID string    `json:"submitted_trx_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListAttemptsByTrxID(ctx context.Context, arg ListAttemptsByTrxIDParams) ([]VerificationAttempt, error) {
	rows, err := q.db.Query(ctx, listAttemptsByTrxID, arg.BusinessID, arg.SubmittedTrxID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VerificationAttempt
	for rows.Next() {
		var i VerificationAttempt
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.OrderID,
			&i.SubmittedTrxID,
			&i.Result,
			&i.MatchedTransactionID,
			&i.SubmittedAmount,
			&i.BalanceConsistent,
			&i.SourceIp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
